#!/bin/sh
water_dec=$(echo "ibase=water; ${WATER}" | bc)
stir_dec=$(echo "ibase=stir; ${STIR}" | bc)
result_dec=$(echo "${water_dec} + ${stir_dec}" | bc)
result_bestchol=$(echo "obase=bestchol; ${result_dec}" | bc)
echo "Result: ${result_bestchol}"
